# Generated by Django 6.0.5 on 2026-06-10 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0004_garmenttype_alter_shopservice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('note', models.TextField(blank=True, max_length=200)),
                ('pickup_address_line', models.CharField(max_length=244)),
                ('pickup_city', models.CharField(max_length=100)),
                ('pickup_district', models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kozhikode', 'Kozhikode'), ('Wayanad', 'Wayanad'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], max_length=50)),
                ('pickup_state', models.CharField(choices=[('Kerala', 'Kerala')], max_length=50)),
                ('pickup_pincode', models.CharField(max_length=40)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('order_status', models.CharField(choices=[('placed', 'PLACED'), ('accepted', 'ACCEPTED'), ('pickup_scheduled', 'PICKUP_SCHEDULED'), ('picked_up', 'PICKED_UP'), ('processing', 'PROCESSING'), ('ready', 'READY'), ('delivered', 'DELIVERED'), ('cancelled', 'CANCELLED')], default='placed', max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('success', 'SUCCESS'), ('failed', 'FAILED')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shops.shop')),
            ],
        ),
    ]
