# Generated by Django 6.0.5 on 2026-06-19 08:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shops', '0004_garmenttype_alter_shopservice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('success', 'SUCCESS'), ('failed', 'FAILED'), ('cancelled', 'CANCELLED')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('garment_name_snapshot', models.CharField(blank=True, max_length=50)),
                ('service_name_snapshot', models.CharField(blank=True, max_length=50)),
                ('unit_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('item_status', models.CharField(choices=[('active', 'ACTIVE'), ('cancelled', 'CANCELLED'), ('rejected', 'REJECTED')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('shop_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shops.shopservice')),
            ],
        ),
    ]
