# Generated by Django 6.0.5 on 2026-09-22 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_number_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('placed', 'PLACED'), ('accepted', 'ACCEPTED'), ('pickup_scheduled', 'PICKUP_SCHEDULED'), ('picked_up', 'PICKED_UP'), ('processing', 'PROCESSING'), ('ready', 'READY'), ('delivered', 'DELIVERED'), ('cancelled', 'CANCELLED')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
