# Generated by Django 5.2.14 on 2026-10-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_orderstatushistory"),
        ("shops", "0006_shopapplicationnotification_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_status", "created_at"],
                name="orders_status_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_status", "created_at"],
                name="orders_payment_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"],
                name="orders_created_at_idx",
            ),
        ),
    ]
