# Generated by Django 6.0.5 on 2026-06-10 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shopservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='garments/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='shopservice',
            options={'ordering': ['shop']},
        ),
        migrations.AlterUniqueTogether(
            name='shopservice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='garment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shop_services', to='shops.garmenttype'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='shopservice',
            unique_together={('shop', 'garment_type', 'service')},
        ),
    ]
