# Generated by Django 5.2.14 on 2026-10-02 04:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_garmenttype_alter_shopservice_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=50)),
                (
                    "description",
                    models.TextField(blank=True, max_length=255),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="service_requests/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_requests",
                        to="shops.service",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_requests",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["shop", "status", "created_at"],
                        name="shops_servi_shop_id_5b88d9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShopApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("access_token_hash", models.CharField(max_length=128)),
                ("owner_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex=r"^\+?[0-9 ()-]{7,15}$",
                            ),
                        ],
                    ),
                ),
                ("shop_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shop_applications/",
                    ),
                ),
                ("address_line", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=50)),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("Thiruvananthapuram", "Thiruvananthapuram"),
                            ("Kollam", "Kollam"),
                            ("Pathanamthitta", "Pathanamthitta"),
                            ("Alappuzha", "Alappuzha"),
                            ("Kottayam", "Kottayam"),
                            ("Idukki", "Idukki"),
                            ("Ernakulam", "Ernakulam"),
                            ("Thrissur", "Thrissur"),
                            ("Palakkad", "Palakkad"),
                            ("Malappuram", "Malappuram"),
                            ("Kozhikode", "Kozhikode"),
                            ("Wayanad", "Wayanad"),
                            ("Kannur", "Kannur"),
                            ("Kasaragod", "Kasaragod"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("Kerala", "Kerala")],
                        max_length=20,
                    ),
                ),
                (
                    "pincode",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid pincode.",
                                regex=r"^[0-9]{3,10}$",
                            ),
                        ],
                    ),
                ),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_shop_application",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_shop",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_application",
                        to="shops.shop",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_shop_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="shops_shopa_status_50c37b_idx",
                    ),
                    models.Index(
                        fields=["email", "created_at"],
                        name="shops_shopa_email_0a43e6_idx",
                    ),
                ],
            },
        ),
    ]
