# Generated by Django 5.2.14 on 2026-10-02 04:48

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def reject_existing_case_insensitive_duplicates(apps, schema_editor):
    Service = apps.get_model("shops", "Service")
    ServiceRequest = apps.get_model("shops", "ServiceRequest")

    service_names = {}
    service_duplicates = []
    for service_id, service_name in Service.objects.values_list("id", "service_name"):
        normalized = service_name.strip().casefold()
        if normalized in service_names:
            service_duplicates.append(
                f"Service ids {service_names[normalized]} and {service_id}: {service_name!r}"
            )
        else:
            service_names[normalized] = service_id

    request_names = {}
    request_duplicates = []
    for request_id, shop_id, service_name in ServiceRequest.objects.filter(
        status__in=("pending", "under_review")
    ).values_list("id", "shop_id", "service_name"):
        key = (shop_id, service_name.strip().casefold())
        if key in request_names:
            request_duplicates.append(
                f"ServiceRequest ids {request_names[key]} and {request_id}: {service_name!r} for shop {shop_id}"
            )
        else:
            request_names[key] = request_id

    if service_duplicates or request_duplicates:
        details = service_duplicates + request_duplicates
        raise RuntimeError(
            "Migration stopped because case-insensitive duplicates must be "
            "reviewed before applying uniqueness constraints: "
            + "; ".join(details[:20])
        )


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_servicerequest_shopapplication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopApplicationNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("approval", "Approval"),
                            ("rejection", "Rejection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=255)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterField(
            model_name="shopapplication",
            name="address_line",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="shopapplication",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="shopapplication",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shopapplication",
            name="district",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Thiruvananthapuram", "Thiruvananthapuram"),
                    ("Kollam", "Kollam"),
                    ("Pathanamthitta", "Pathanamthitta"),
                    ("Alappuzha", "Alappuzha"),
                    ("Kottayam", "Kottayam"),
                    ("Idukki", "Idukki"),
                    ("Ernakulam", "Ernakulam"),
                    ("Thrissur", "Thrissur"),
                    ("Palakkad", "Palakkad"),
                    ("Malappuram", "Malappuram"),
                    ("Kozhikode", "Kozhikode"),
                    ("Wayanad", "Wayanad"),
                    ("Kannur", "Kannur"),
                    ("Kasaragod", "Kasaragod"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="shopapplication",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="shopapplication",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shopapplication",
            name="owner_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="shopapplication",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number.",
                        regex=r"^\+?[0-9 ()-]{7,15}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="shopapplication",
            name="pincode",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid pincode.",
                        regex=r"^[0-9]{3,10}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="shopapplication",
            name="shop_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="shopapplication",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[("Kerala", "Kerala")],
                max_length=20,
            ),
        ),
        migrations.RunPython(
            reject_existing_case_insensitive_duplicates,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("service_name")
                ),
                name="shops_service_name_ci_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("service_name")
                ),
                models.F("shop"),
                condition=models.Q(
                    ("status__in", ("pending", "under_review"))
                ),
                name="shops_sr_shop_active_name_uniq",
            ),
        ),
        migrations.AddField(
            model_name="shopapplicationnotification",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="shops.shopapplication",
            ),
        ),
        migrations.AddIndex(
            model_name="shopapplicationnotification",
            index=models.Index(
                fields=["status", "created_at"],
                name="shops_shopa_status_8fc98b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="shopapplicationnotification",
            constraint=models.UniqueConstraint(
                fields=("application", "notification_type"),
                name="shops_app_notification_type_uniq",
            ),
        ),
    ]
