# Generated by Django 6.0.5 on 2026-06-25 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_order_order_number_alter_order_total_amount_and_more'),
        ('shops', '0004_garmenttype_alter_shopservice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_starts_at', models.TimeField()),
                ('shift_ends_at', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_agents', to='shops.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('pickup', 'PICKUP'), ('delivery', 'DELIVERY')], max_length=50)),
                ('status', models.CharField(choices=[('unassigned', 'UNASSIGNED'), ('assigned', 'ASSIGNED'), ('in_progress', 'IN_PROGRESS'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='unassigned', max_length=50)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_tasks', to='logistics.deliveryagent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tasks', to='orders.order')),
            ],
            options={
                'unique_together': {('order', 'task_type')},
            },
        ),
    ]
