# Generated by Django 6.0.5 on 2026-07-03 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('orders', '0003_alter_order_order_number_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='task_type',
            field=models.CharField(blank=True, choices=[('pickup', 'PICKUP'), ('delivery', 'DELIVERY')], max_length=20),
        ),
    ]
