# Generated by Django 6.0.5 on 2026-07-03 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_deliverytask_order_and_more'),
        ('orders', '0003_alter_order_order_number_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_tasks', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='task_type',
            field=models.CharField(choices=[('pickup', 'PICKUP'), ('delivery', 'DELIVERY')], max_length=20),
        ),
    ]
