# Generated by Django 6.0.5 on 2026-06-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('shop_admin', 'Shop Admin'), ('delivery_agent', 'Delivery Agent'), ('platform_admin', 'Platform Admin')], max_length=20),
        ),
    ]
