# Generated by Django 5.2.14 on 2026-09-30 13:22

from django.db import migrations, models


def normalize_legacy_emails(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(email="").update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
            ),
        ),
        migrations.RunPython(
            normalize_legacy_emails,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
    ]
